<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Relatedproducts
 * @version    1.4.4
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $collection = $this->getRelatedProductsCollection(); ?>
<?php if($this->getEnabled() && count($collection)): ?>
<div class="aw-box aw-mini-related-items block aw-arp-block">
    <div class="block-title">
                <strong><span><?php echo $this->__('Customers Who Bought This Also Bought') ?></span></strong>
            </div>
    <div class="aw-content block-related-product aw-arp-block-content" <?php if (Mage::helper('relatedproducts')->checkVersion('1.4.1.0')) { echo "id=\"after1400\""; }?>>
        <?php foreach($collection as $_item): ?>
        <div class="aw-arp-item">
            
                <a href="<?php echo $_item->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(168) ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" width="168" height="168" /></a>
                    
                    <?php echo $this->getPriceHtml($_item, true); ?>
                    <a class="aw-product-name" href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a>
                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="aw-link-cart"><?php echo $this->__('Add to Wishlist') ?></a>
                    <?php endif; ?>
        </div>
        <?php endforeach ?>
    </div>
</div>
<script type="text/javascript">
<!--
$$('.aw-related-checkbox').each(function(elem){
    Event.observe(elem, 'click', addAwRelatedToProduct)
});

var relatedAwProductsCheckFlag = false;
function selectAllAwRelated(txt){
    if (relatedAwProductsCheckFlag == false) {
        $$('.aw-related-checkbox').each(function(elem){
            elem.checked = true;
        });
        relatedAwProductsCheckFlag = true;
        txt.innerHTML="<?php echo $this->__('unselect all') ?>";
    } else {
        $$('.aw-related-checkbox').each(function(elem){
            elem.checked = false;
        });
        relatedAwProductsCheckFlag = false;
        txt.innerHTML="<?php echo $this->__('select all') ?>";
    }
    addAwRelatedToProduct();
}

function addAwRelatedToProduct(){
    var checkboxes = $$('.aw-related-checkbox');
    var values = [];
    for(var i=0;i<checkboxes.length;i++){
        if(checkboxes[i].checked) values.push(checkboxes[i].value);
    }
    
    if($('related-products-field')){
        $('related-products-field').value = values.join(',');
    }
    
}
//-->
</script>
<?php endif ?>