<?php
/**
* Product list template which will be used in Newsletter subscribe.
*
* @see Fiuze_Setup_Block_Products
* @author Ron Brown
*/

$_columnCount = 3; // Products in a column

$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');

?>

<?php
function ShortenText($text, $chars) {

        // Change to the number of characters you want to display
        //$chars = 120;
        $text = $text." ";
        $text = substr($text,0,$chars);
        $text = substr($text,0,strrpos($text,' '));
        $text = $text."...";

        return $text;

    }
?>

<?php if(!$_productCollection->count()): ?>
    <!-- <p style="color:#df280a; border: 1px solid #f16048; background: #faebe7; font:12px/1.5em Arial, Helvetica, sans-serif;padding: 5px 8px 2px 32px; margin:10px 0;">
        <?php //echo $this->__('There are no products matching the selection.') ?>
    </p> -->
<?php else: //We have products, and we are going to show them in grid mode.?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <!-- <ul class="products-grid"> -->
        <?php endif ?>
        <?php if($_product->isSaleable()): ?>
        <li class="item">
            <!-- <li class="item<?php //if(($i-1)%$_columnCount==0): ?> first<?php //elseif($i%$_columnCount==0): ?> last<?php //endif; ?>"> -->
            <div class="products-grid-image-container">
                <ul class="alerts-container">

                    <!-- ** Inventory qty display ** -->

                    <?php if($_product->isSaleable()){

                        $productQty =  (int)Mage::getModel('cataloginventory/stock_item')->loadByProduct($_product)->getQty();

                        if($productQty == 0){?>
                            <!-- <li class="alert-banner soldout"><?php //echo $this->__('Soldout') ?><?php //echo $productQty ?></li> -->
                        <?php } elseif ($productQty == 1){?>
                            <li class="alert-banner hotitem"><?php echo $this->__('Hurry! Just ') ?><?php echo $productQty; ?><?php echo $this->__(' left!') ?></li>
                        <?php } elseif ($productQty <= 10){?>
                            <li class="alert-banner hotitem"><?php echo $this->__('Only ') ?><?php echo $productQty; ?><?php echo $this->__(' left') ?></li>
                        <?php } ?>
                    <?php } else { ?>
                        <li class="alert-banner soldout"><?php echo $this->__('Soldout') ?></li>
                    <?php } ?>

                    <!-- ** New item display ** -->
                    <?php
                        $now = date('Y-m-d');
                        $newsFrom= substr($_product->getData('news_from_date'),0,10);
                        $newsTo=  substr($_product->getData('news_to_date'),0,10);

                        if (($now>=$newsFrom && $now<=$newsTo)||($now>=$newsFrom && $newsFrom!='' && $newsTo=='' ))
                        {?>
                            <li class="alert-banner newitem">New Item</li>
                    <?php }?>

                    </ul> <!-- end alerts container -->

                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(298); ?>" width="298" height="298" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            </div> <!-- end grid image container -->

                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>

                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <a class="view-deal-btn" href="<?php echo $_product->getProductUrl() ?>">View Deal</a>
                    <?php else: ?>
                        <a class="soldout-btn">Sold Out</a>
                    <?php endif; ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>

                <?php echo $this->getPriceHtml($_product, true) ?>

                <!-- newsletter shortened title -->
                <?php
                    $newsletterTitle = $_helper->productAttribute($_product, $_product->getName(), 'name');
                ?>
                <h2 class="product-index-description-container">
                    <?php 
                        if (strlen($newsletterTitle) > 70) {
                            echo ShortenText($newsletterTitle, 70);
                        } else {
                            echo ($newsletterTitle);
                        }
                    ?>
                </h2>
                
                <!-- newsletter shortened desc -->
                <?php
                    $newsletterShortDesc = $_product->getShortDescription();
                ?>
                <p class="newsletter-short-desc">
                    <?php //echo $_product->getShortDescription(); ?>
                    <?php 
                        if (strlen($newsletterShortDesc) > 140) {
                            echo ShortenText($newsletterShortDesc, 160);
                        } else {
                            echo ($newsletterShortDesc);
                        }
                    ?>
                </p>
            </li>
            <?php endif ?>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        <!-- </ul> -->
        <?php endif ?>
        <?php endforeach ?>

    <?php endif; ?>

