<?php
$row = $this->getObject() ?>

<table cellspacing="0" cellpadding="0" border="0" width="100%" style="border:1px solid #bebcb7; background:#f8f7f5;">
    <thead>
        <tr>
            <th align="left" bgcolor="#d9e5ee" style="padding:3px 9px">
                <strong><?php echo $this->__('Tracking number:'); ?></strong>
            </th>
            <th align="left" bgcolor="#d9e5ee" style="padding:3px 9px">
                <strong><?php echo $this->__('Status:'); ?></strong>
            </th>
            <th align="left" bgcolor="#d9e5ee" style="padding:3px 9px">
                <strong><?php echo $this->__('Order id:'); ?></strong>
            </th>
            <th align="left" bgcolor="#d9e5ee" style="padding:3px 9px">
                <strong><?php echo $this->__('Message:'); ?></strong>
            </th>
        </tr>
    </thead>

    <tbody>
        <?php foreach($row as $key => $value): ?>
            <tr>
                <td align="left" style="padding:3px 9px; border: 1px solid black;">
                    <strong><?php echo $key; ?></strong>
                </td>

                <td align="left" style="padding:3px 9px; border: 1px solid black;">
                    <strong><?php echo $value['status']; ?></strong>
                </td>

                <td align="left" style="padding:3px 9px; border: 1px solid black;">
                    <strong><?php echo $value['orderId']; ?></strong>
                </td>

                <td align="left" style="padding:3px 9px; border: 1px solid black;">
                    <strong><?php echo $value['message']; ?></strong>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>


