<div class="account-create">
    <div class="page-title">
        <h1><?php echo Mage::helper('newsletterbooster')->__('Unsubscribe NewsletterBooster Campaign') ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostSaveActionUrl() ?>" method="post" id="form-validate">
        <div class="fieldset">
            <h2 class="legend"><?php echo Mage::helper('newsletterbooster')->__('Subscriber Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="email" class="required"><em>*</em><?php echo Mage::helper('newsletterbooster')->__('Email') ?></label>
                        <div class="input-box">
                            <input type="text" name="email" id="email" title="<?php echo Mage::helper('newsletterbooster')->__('Email') ?>" class="input-text required-entry" />
                        </div>
                    </div>
                    <input type="hidden" name="campaign" value="<?php echo $this->getRequest()->getParam('id') ?>" />
                    <input type="hidden" name="entity" value="<?php echo $this->getRequest()->getParam('entity') ?>" />
                    <input type="hidden" name="queue" value="<?php echo $this->getRequest()->getParam('queue') ?>" />
                </li>
            </ul>
        </div>
        <div class="buttons-set">
            <p class="required"><?php echo Mage::helper('newsletterbooster')->__('* Required Fields') ?></p>
            <button type="submit" title="<?php echo Mage::helper('newsletterbooster')->__('Unsubscribe') ?>" class="button"><?php echo Mage::helper('newsletterbooster')->__('Unsubscribe') ?></button>
        </div>
    </form>
</div>