<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="head-dashboard"><?php echo Mage::helper('newsletterbooster')->__('NesletterBooster dashboard') ?></h3></td>
        </tr>
    </table>
</div>
<div class="dashboard-container">
    <?php echo $this->getChildHtml('store_switcher') ?>
    <table cellspacing="25" width="100%">
        <tr>
            <td><?php echo $this->getChildHtml('campaign') ?>
                <div class="entry-edit">
                    <div class="entry-edit-head"><h4><?php echo Mage::helper('newsletterbooster')->__('Last 5 campaigns') ?></h4></div>
                    <fieldset class="np"><?php echo $this->getChildHtml('lastCampaigns'); ?></fieldset>
                </div>
                <div class="entry-edit">
                    <div class="entry-edit-head"><h4><?php echo Mage::helper('newsletterbooster')->__('Last 5 sended newsletter') ?></h4></div>
                    <fieldset class="np"><?php echo $this->getChildHtml('lastQueue'); ?></fieldset>
                </div>
            </td>
            <td>
                <div class="entry-edit" style="border:1px solid #ccc;">
                    <?php echo $this->getChildHtml('diagrams') ?>
                    <?php if (is_array($this->getChild('diagrams')->getTabsIds())) : ?>
                        <div id="diagram_tab_content"></div>
                    <?php endif; ?>
                </div>
            </td>
        </tr>
    </table>
</div>
