<?php 
    $helper = Mage::helper('newsletterbooster');
    $campaigns = $this->getCampaigns();
    $customerCamp = $this->getCustomerCampaigns();
?>
<div class="page-title">
    <h1><?php echo $helper->__('My Newsletter Subscriptions') ?></h1>
</div>
<?php if($campaigns->getSize()): ?>
<form action="<?php echo $this->getUrl('newsletterbooster/customer/subscribe') ?>" method="post" id="form-validate">
<table class="data-table" id="my-campaign-table" >
    <thead>
        <tr>
            <th><?php echo $helper->__('#') ?></th>
            <th><?php echo $helper->__('Campaign Title') ?></th>
            <th><?php echo $helper->__('Description') ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($campaigns as $campaign): ?>
        <tr>
            <td align="center">
                <input 
                    type="checkbox" 
                    name="campaigns[]"  
                    value="<?php echo $campaign->getId() ?>"  
                    title="<?php echo Mage::helper('newsletterbooster')->__('Subscribe/Unsubscribe') ?>"
                    <?php if(in_array($campaign->getId(), $customerCamp)) : ?> checked="checked"<?php endif; ?> 
                    class="checkbox" />
            </td>
            <td><?php echo $campaign->getTemplateCode() ?>&nbsp;</td>
            <td><?php echo $campaign->getDescription() ?>&nbsp;</td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
<input type="hidden" name="subscriber" value="<?php echo $this->getCustomer()->getId() ?>" />

<script type="text/javascript">decorateTable('my-campaign-table')</script>
<?php else: ?>
    <p><?php echo $this->__('You have no subscribe yet.') ?></p>
<?php endif ?>
<div class="buttons-set">
    <button type="submit" title="<?php echo Mage::helper('newsletterbooster')->__('Save Changes') ?>" class="button">
        <span><span><?php echo Mage::helper('newsletterbooster')->__('Save Changes') ?></span></span>
    </button>
    <p class="back-link"><a href="<?php echo $this->getUrl('customer/account') ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>
</form>