<?php
/**
 * @author		Sashas
* @category    Sashas
* @package     Sashas_OrderSuccessPage
* @copyright   Copyright (c) 2013 Sashas IT Support Inc. (http://www.sashas.org)
* @license     http://opensource.org/licenses/GPL-3.0  GNU General Public License, version 3 (GPL-3.0)
*/
?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<h2 class="sub-title"><?php echo $this->__('Thank you for your purchase!') ?></h2>

<?php

$orderId = $this->getOrderId(); 
$order = Mage::getModel('sales/order')->loadByIncrementId($orderId); 
$total = $order->getGrandTotal(); 
$subtotal = $order->getSubtotal(); 
$discount = $order->getDiscountAmount(); 
$affiliateTotal = ($subtotal + $discount);

$ordered_items = $order->getAllVisibileItems();
$skulist = ''; //setup skulist param
$pricelist = ''; //setup pricelist param
$quantitylist = ''; //setup quantitylist param

foreach($ordered_items as $item){
	$skulist .= $item->getSku() . ',';
    $quantitylist .= $item->getQtyOrdered() . ',';
    $pricelist .= $item->getProduct()->getFinalPrice() . ',';
}
//not totally necessary, but cleans up the trailing commas at the end of each skulist, pricelist, quantitylist param
$skulist = substr($skulist, 0, -1);
$quantitylist = substr($quantitylist, 0, -1);
$pricelist = substr($pricelist, 0, -1);
//Magento has only one couponcode allowed, so no comma-separated list to make
$couponcodes = $order->getCouponCode(); 

$newcustomer = ''; //setup newcustomer param
$customer = $order->getCustomerId();
if($customer){
	$_orders = Mage::getModel('sales/order')->getCollection()->addFieldToFilter('customer_id', $customer);                        
	$_orderCnt = $_orders->count(); //orders count
	//if customer has more than an order, they're not new
	$newcustomer = ($_orderCnt > 1 ? 0 : 1);
}
//setup currency code
$currency = $order->getOrderCurrencyCode();
?>
<img src="https://shareasale.com/sale.cfm?tracking=<?php echo $orderId ?>&amount=<?php echo $affiliateTotal ?>&transtype=sale&merchantID=51523&couponcode=<?php echo $couponcodes ?>&skulist=<?php echo $skulist ?>&quantitylist=<?php echo $quantitylist ?>&pricelist=<?php echo $pricelist ?>&newcustomer=<?php echo $newcustomer ?>&currency=<?php echo $currency ?>" width="1" height="1">

<?php if ($this->getOrderId()):?>
    <p><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?>
       <?php //echo $this->__('Click <a href="%s" onclick="this.target=\'_blank\'">here to print</a> a copy of your order confirmation.', $this->getUrl('ordersuccesspage/ordersuccesspage/print',array('id',Mage::registry('current_order')->getId()))) ?> 
    </p>
 
<?php endif;?>

<?php if ($this->getAgreementRefId()): ?>
    <p><?php echo $this->__('Your billing agreement # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getAgreementUrl()), $this->escapeHtml($this->getAgreementRefId())))?></p>
<?php endif;?>

<?php if ($profiles = $this->getRecurringProfiles()):?>
<p><?php echo $this->__('Your recurring payment profiles:'); ?></p>
<ul class="disc">
<?php foreach($profiles as $profile):?>
<?php $profileIdHtml = ($this->getCanViewProfiles() ? sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getProfileUrl($profile)), $this->escapeHtml($this->getObjectData($profile, 'reference_id'))) : $this->escapeHtml($this->getObjectData($profile, 'reference_id')));?>
    <li><?php echo $this->__('Payment profile # %s: "%s".', $profileIdHtml, $this->escapeHtml($this->getObjectData($profile, 'schedule_description')))?></li>
<?php endforeach;?>
</ul> 
<?php endif;?>
<?php if ($this->getOrderId()):?>
<?php
$orderObj = Mage::getModel('sales/order')->loadByIncrementId($this->getOrderId());
?>
<?php echo $this->getLayout()->createBlock('sales/order_info')->setTemplate('ordersuccesspage/info.phtml')->toHtml();?> 
<?php echo $this->getLayout()->createBlock('sales/order_items')->setTemplate('ordersuccesspage/items.phtml')->toHtml();?> 
<?php endif;?>
<div class="buttons-set">
    <button type="button" class="button" title="<?php echo $this->__('Continue Shopping') ?>" onclick="window.location='<?php echo $this->getUrl() ?>'"><?php echo $this->__('Continue Shopping') ?></button>
</div>

<!-- conversion value for Adroll smart pixel -->

<script type="text/javascript">
  adroll_conversion_value_in_dollars = <?php echo($subtotal); ?>;
  adroll_custom_data = {"ORDER_ID": <?php echo($this->getOrderId()); ?>};
</script>

<!-- BEGIN OF FLEXOFFERS.COM TRACKING CODE -->

<img src="http://track.flexlinks.com/tracker.aspx?AID=b6c1c199-5003-49c0-bcb1-87f1839155cf&AMT=<?php echo($subtotal); ?>&CMM=&UID=<?php echo($this->getOrderId()); ?>" width="1" height="1" alt=""/>

<!-- END OF FLEXOFFERS.COM TRACKING CODE -->

<!-- Google Code for Daily Sale Conversion Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 1003172301;
var google_conversion_language = "en";
var google_conversion_format = "2";
var google_conversion_color = "ffffff";
var google_conversion_label = "xLwaCJCAtFgQzeOs3gM";
var google_conversion_value = 1.00;
var google_conversion_currency = "USD";
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/1003172301/?value=1.00&amp;currency_code=USD&amp;label=xLwaCJCAtFgQzeOs3gM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

<!-- START Google Trusted Stores Order -->
<div id="gts-order" style="display:none;" translate="no">

  <!-- start order and merchant information -->
  <span id="gts-o-id">MERCHANT_ORDER_ID</span>
  <span id="gts-o-domain">MERCHANT_ORDER_DOMAIN</span>
  <span id="gts-o-email">CUSTOMER_EMAIL</span>
  <span id="gts-o-country">CUSTOMER_COUNTRY</span>
  <span id="gts-o-currency">CURRENCY</span>
  <span id="gts-o-total">ORDER_TOTAL</span>
  <span id="gts-o-discounts">ORDER_DISCOUNTS</span>
  <span id="gts-o-shipping-total">ORDER_SHIPPING</span>
  <span id="gts-o-tax-total">ORDER_TAX</span>
  <span id="gts-o-est-ship-date">ORDER_EST_SHIP_DATE</span>
  <span id="gts-o-est-delivery-date">ORDER_EST_DELIVERY_DATE</span>
  <span id="gts-o-has-preorder">HAS_BACKORDER_PREORDER</span>
  <span id="gts-o-has-digital">HAS_DIGITAL_GOODS</span>
  <!-- end order and merchant information -->

  <!-- start repeated item specific information -->
  <!-- item example: this area repeated for each item in the order -->
  <span class="gts-item">
    <span class="gts-i-name">ITEM_NAME</span>
    <span class="gts-i-price">ITEM_PRICE</span>
    <span class="gts-i-quantity">ITEM_QUANTITY</span>
    <span class="gts-i-prodsearch-id">ITEM_GOOGLE_SHOPPING_ID</span>
    <span class="gts-i-prodsearch-store-id">ITEM_GOOGLE_SHOPPING_ACCOUNT_ID</span>
    <span class="gts-i-prodsearch-country">ITEM_GOOGLE_SHOPPING_COUNTRY</span>
    <span class="gts-i-prodsearch-language">ITEM_GOOGLE_SHOPPING_LANGUAGE</span>
  </span>
  <!-- end item 1 example -->
  <!-- end repeated item specific information -->

</div>
<!-- END Google Trusted Stores Order -->
