<script>
    <?php
        $productActive = Mage::getResourceModel('fiuze_deals/deals_collection')
            ->addFilter('current_active', 1)->getFirstItem();
    ?>
    function timer() {
        var now = new Date();
        var nowDate = new Date(now.getTime() + now.getTimezoneOffset() * 60000);
        var achiveDate = new Date('<?php echo $productActive->getData('end_time') ?>');//end time
        var result = (achiveDate - nowDate) + 1000;
        if (result < 0) {
            var elmntNew = document.getElementById('timer');
            elmntNew.innerHTML = ' 00 : 00 : 00 ';
            return undefined;
        }
        var seconds = Math.floor((result / 1000) % 60);
        var minutes = Math.floor((result / 1000 / 60) % 60);
        var hours = Math.floor((result / 1000 / 60 / 60) % 24);
        if (seconds < 10) seconds = '0' + seconds;
        if (minutes < 10) minutes = '0' + minutes;
        if (hours < 10) hours = '0' + hours;
        var elmnt = document.getElementById('timer');
        elmnt.innerHTML = hours + ':' + minutes + ':' + seconds;
        setTimeout(timer, 1000);
    }
    window.onload = function () {
        timer();
    };
</script>


