<?php
$isPartial = $this->isPartialPayment();
$isCheckedCustomercredit = Mage::getSingleton('checkout/session')->getUseInternalCredit();
if ($isPartial==2 && $isCheckedCustomercredit) $this->getQuote()->getPayment()->setMethod('customercredit');
?>
<script type="text/javascript">
    var creditPayment;
</script>
<div class="onestepcheckout-payment-methods">
    <dl class="sp-methods" id="checkout-payment-method-load">
        <?php $i=0;?>
        <?php foreach ($this->getMethods() as $_method):
            $_code = $_method->getCode();
            $_code = $_method->getCode();
            if ($_code=='customercredit' && $isPartial == -2) continue; // hide customer credit
            ?>
            <?php $i++;?>
            <?php if($i != count($this->getMethods())):?>
            <style type="text/css">
                #advice-validate-one-required-by-name-p_method_<?php echo $_code ?>{
                    display: none !important;
                }
            </style>
        <?php endif;?>
            <dt>
                <?php if( sizeof($this->getMethods()) > 1 ): ?>
                    <?php if ($_code=='customercredit' && $isPartial==1): ?>

                        <input id="p_method_<?php echo $_code ?>" value="customercredit" type="checkbox" name="payment[use_internal_credit]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" class="checkbox" onclick="save_shipping_method(shipping_method_url,true, true, 'checkbox')" <?php if ($isCheckedCustomercredit) { ?>checked="checked"<?php } ?> />
                    <?php elseif ($_code=='customercredit' && $isPartial==-1): ?>
                        <input id="p_method_<?php echo $_code ?>_disabled" disabled="disabled" value="1" type="checkbox" name="payment[use_internal_credit]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" class="checkbox" />
                    <?php elseif ($_code=='customercredit' && $isPartial==0) : ?>
                        <input id="p_method_<?php echo $_code ?>_disabled" disabled="disabled" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" class="radio" />
                    <?php else: ?>
                        <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" class="radio" onclick="save_shipping_method(shipping_method_url);"<?php if($this->getSelectedMethodCode()==$_code): ?> checked="checked"<?php endif; ?> />
                    <?php endif; ?>

                <?php else: ?>
                    <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="radio validate-one-required-by-name " onclick="save_shipping_method(shipping_method_url);" /></span>
                <?php endif; ?>
                <label for="p_method_<?php echo $_code ?>">
                    <?php echo $this->getMethodTitle($_method) ?> <?php echo $this->getMethodLabelAfterHtml($_method);
                    if ($_code=='customercredit' && Mage::helper('customercredit')->isEnabledCodes()) {?>
                        (<a href="<?php echo $this->getUrl('customercredit/') ?>" target="_blank">
                            <?php echo Mage::helper('customercredit')->__('Recharge') ?></a>)
                    <?php } ?>
                </label>

            </dt>
            <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
            <dd id="container_payment_method_<?php echo $_code; ?>" class="payment-method">
                <?php echo $html; ?>
            </dd>
        <?php endif; ?>
        <?php endforeach; ?>
    </dl>
</div>
<div class="tool-tip" id="payment-tool-tip" style="display:none;">
    <div class="btn-close"><a href="#" id="payment-tool-tip-close" title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a></div>
    <div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
</div>
<script type="text/javascript">
    //<![CDATA[
    $$('#checkout-payment-method-load dt input').invoke('observe', 'click', function(e) {


        var element = e.element();
        var name = 'payment_form_' + element.value;

        /* Hide all other forms */
        if(element.type!='checkbox') {
            $$('dd.payment-method').invoke('hide');
        }
        if(element.checked) {
            var form = $(name);
            var container = $('container_payment_method_' + element.value);

            if(element !== null && container !== null)    {
                container.show();
                $(name).show();
            }
        }

    });
    //]]>
</script>
<script type="text/javascript">
    //<![CDATA[
    function toggleToolTip(event){
        if($('payment-tool-tip')){
            $('payment-tool-tip').setStyle({
                top: (Event.pointerY(event)-560)+'px'//,
                //left: (Event.pointerX(event)+100)+'px'
            })
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }
    if($('payment-tool-tip-close')){
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }

    initWhatIsCvvListeners();
    //]]>
</script>