<div class="notice">
    <h4>
		<?php echo Mage::helper('dyncatprod')->__('<strong style="color:#EA7601;">Installed version is %s</strong>', $this->getVersion()); ?>
    </h4>
    <?php if($importExport = $this->isImportExportInstalled()): ?>
        <h4>
            <?php echo Mage::helper('dyncatprod')->__('<strong style="color:#EA7601;">Import / Export installed version is %s</strong>', $importExport); ?>
        </h4>
    <?php else: ?>
        <h6>Need import / export?</h6>
    <?php endif; ?>
    <h5>
        <br/>
        <?php echo Mage::helper('dyncatprod')->__('<a href="https://twitter.com/ProxiBlue" target="_blank">Follow ProxiBlue to get new features notifications!</a>'); ?>
    </h5>
    <h6>
        <?php echo Mage::helper('dyncatprod')->__('<a href="http://support.proxiblue.com.au" target="_blank">Need support? Visit suport.proxiblue.com.au</a>'); ?>
    </h6>
    <br/>
</div>