<?php if ($this->CampaignSelected()) : ?>
    <?php $sendData = $this->getQueueSendData(); ?>
    <?php $opensData = $this->getQueueOpensData(); ?>
    <?php $clicksData = $this->getQueueClicksData(); ?>
    <?php $unOpensData = $this->getQueueUnOpensData(); ?>
    <?php $unsubscribeData = $this->getQueueUnsubscribeData(); ?>
    <?php $errorData = $this->getQueueErrorsData(); ?>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = new google.visualization.DataTable();
            data.addColumn('string', '<?php echo Mage::helper('newsletterbooster')->__('Queue') ?>');
            data.addColumn('number', '<?php echo Mage::helper('newsletterbooster')->__('Values') ?>');
            data.addColumn({type:'string', role:'tooltip'});
            data.addRows(6);
            data.setValue(0, 0, '<?php echo Mage::helper('newsletterbooster')->__('Sended') ?>');
            data.setValue(0, 1, <?php echo $sendData['send'] ?>);
            data.setValue(0, 2, '<?php echo $sendData['tooltip'] ?>');
            data.setValue(1, 0, '<?php echo Mage::helper('newsletterbooster')->__('Opens') ?>');
            data.setValue(1, 1, <?php echo $opensData['opens'] ?>);
            data.setValue(1, 2, '<?php echo $opensData['tooltip'] ?>');
            data.setValue(2, 0, '<?php echo Mage::helper('newsletterbooster')->__('Clicks') ?>');
            data.setValue(2, 1, <?php echo $clicksData['clicks'] ?>);
            data.setValue(2, 2, '<?php echo $clicksData['tooltip'] ?>');
            data.setValue(3, 0, '<?php echo Mage::helper('newsletterbooster')->__('Unopens') ?>');
            data.setValue(3, 1, <?php echo $unOpensData['unopens'] ?>);
            data.setValue(3, 2, '<?php echo $unOpensData['tooltip'] ?>');
            data.setValue(4, 0, '<?php echo Mage::helper('newsletterbooster')->__('Unsubscribe') ?>');
            data.setValue(4, 1, <?php echo $unsubscribeData['unsubscribe'] ?>);
            data.setValue(4, 2, '<?php echo $unsubscribeData['tooltip'] ?>');
            data.setValue(5, 0, '<?php echo Mage::helper('newsletterbooster')->__('Errors') ?>');
            data.setValue(5, 1, <?php echo $errorData['errors'] ?>);
            data.setValue(5, 2, '<?php echo $errorData['tooltip'] ?>');

        var options = {
          width: 650,
          height: 350,
          title: '<?php echo Mage::helper('newsletterbooster')->__('Statistic') ?>',
          vAxis: {
              minValue: 0
          }
        };

        var chart = new google.visualization.ColumnChart(document.getElementById('tracks_queue'));
        chart.draw(data, options);

      }
    </script>

    <div id="tracks_queue" style="width: 650px; height: 350px;"></div>
<?php else : ?>
    <p class="a-center" style="width:650px;height:350px; margin:0 auto;">
        <?php echo Mage::helper('newsletterbooster')->__('No active campaign choosen.') ?>
    </p>
<?php endif; ?>
