<?php if (Mage::getStoreConfig('newsletterbooster/subscribe/enabled')) : ?>
<?php $items = $this->getCampaignsForSubscribe(); ?>
<div class="block block-subscribe">
    <div class="block-title">
        <strong><span><?php echo $this->__('Newsletter') ?></span></strong>
    </div>
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
        <div class="block-content">
            <div class="form-subscribe-header">
                <label for="newsletter">
                    <?php echo Mage::helper('newsletterbooster')->__('Select Campaigns:') ?>
                </label>
            </div>
            <div class="input-box">
                <ul>
                    <?php foreach ($items as $_item) : ?>
                        <li style="margin: 5px 0;">
                            <input 
                                class="checkbox related-checkbox" 
                                type="checkbox" 
                                id="related-checkbox<?php echo $_item['campaign_id'] ?>"
                                name="campaigns[]" 
                                value="<?php echo $_item['campaign_id'] ?>" />
                            <label for="related-checkbox<?php echo $_item['campaign_id'] ?>"><?php echo $_item['template_code'] ?></label>
                        </li>
                    <?php endforeach ?>
                </ul>
            </div>
            <label for="firstname">
                    <?php echo $this->__('First Name') ?>
            </label>
            <div class="input-box">
               <input 
                    type="text" 
                    name="firstname" 
                    id="firstname" 
                    title="<?php echo $this->__('First Name') ?>" 
                    class="input-text" />
            </div>
            <label 
                for="lastname">
                    <?php echo $this->__('Last Name') ?>
            </label>
            <div class="input-box">
               <input 
                    type="text" 
                    name="lastname" 
                    id="lastname" 
                    title="<?php echo $this->__('Last Name') ?>" 
                    class="input-text" />
            </div>
            <label for="email" class="required">
                <?php echo $this->__('Email') ?>
            </label>
            <div class="input-box">
               <input 
                    type="text" 
                    name="email" 
                    id="newsletter" 
                    title="<?php echo $this->__('Sign up for our newsletter') ?>" 
                    class="input-text required-entry validate-email" />
            </div>
            <input type="hidden" name="redirect" value="<?php echo Mage::helper('core/url')->getCurrentUrl() ?>" />
            <div class="actions">
                <button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button">
                    <span><span><?php echo $this->__('Subscribe') ?></span></span></button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
    </script>
</div>
<?php endif; ?>