<?php $kickers = array() ?>
<?php foreach($this->getKickerList() as $key => $array): ?>
	<?php $kickers[$array['value']] = $array['label'] ?>
<?php endforeach ?>
<?php if($this->isEnabled() && $this->hasHash()): ?>
	<?php if($this->getIsSidebar()): ?>
		<div class="block">
			<div class="block-content a-center">
	<?php endif ?>
				<div id="buySAFE_Kicker" name="buySAFE_Kicker" type="<?php echo $kickers[$this->getKicker()] ?>" <?php if($class = $this->getClass()){ echo 'class="'.$class.'"'; }; if($style = $this->getStyle()){ echo 'style="'.$style.'"'; } ?>></div>
	<?php if($this->getIsSidebar()): ?>
			</div>
		</div>
	<?php endif ?>
<?php endif ?>